version: "3"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: dss-postgres
    container_name: dss-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres12345
      - PGPASSWORD=postgres12345
      - POSTGRES_DB=dsdojo_db
      - DATABASE_HOST=localhost
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - ./docker/work/data:/tmp/data
      - dss-postgres-data:/var/lib/postgresql/data

volumes:
  dss-postgres-data:
    external: true