version: "3"

services:
  dss-db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: dss-postgres
    container_name: dss-postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=padawan
      - POSTGRES_PASSWORD=padawan12345
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - ./docker/work/data:/tmp/data
      - dss-postgres-data:/var/lib/postgresql/data

volumes:
  dss-postgres-data:
    external: true